CREATE TABLE BREED (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

CREATE TABLE TYPE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    BREED_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BREED_ID) REFERENCES BREED(ID)
);
